# =========================================================
# APPLICATION CONFIGURATION
# =========================================================
spring.application.name=Online Book Library
server.port=8080

# =========================================================
# DATABASE CONFIGURATION (Aiven Cloud MySQL)
# =========================================================
spring.datasource.url=jdbc:mysql://mysql-3a4930b-ddou27300-770a.l.aivencloud.com:20788/book_library_db?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_YEcbTm3oUGI2ZCyTp02
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =========================================================
# JPA / HIBERNATE CONFIGURATION
# =========================================================
# ទុកជា create សិនដើម្បីឱ្យវាបង្កើត Tables ថ្មីចូលទៅក្នុង defaultdb របស់ Aiven Cloud រួចរាល់ចាំប្តូរទៅ update
spring.jpa.hibernate.ddl-auto
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================================================
# THYMELEAF CONFIGURATION
# =========================================================
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.mode=HTML

# =========================================================
# FILE UPLOAD CONFIGURATION
# =========================================================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# =========================================================
# SUPABASE CLOUD STORAGE CONFIGURATION
# =========================================================
# បំពេញទិន្នន័យជាក់ស្តែងតាមស្គ្រីនសតរបស់អ្នក ដើម្បីឱ្យប្រព័ន្ធអាច Upload សៀវភៅបាន
app.supabase.url=https://aaglrngfbjhhbyrdtndx.supabase.co
app.supabase.anon-key=sb_publishable_2b6PpgRBQvdtO2Y2A3KqCA_QQzjm6A36b69bdece9e8df31bf9bbd4ef5754020a
app.supabase.bucket=books

# =========================================================
# LOGGING CONFIGURATION
# =========================================================
logging.level.com.library=DEBUG
logging.level.org.springframework.security=INFO